[2024-09-21T21:30:01.546+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_ingestion.spark_raw_ingestion_posicao scheduled__2024-09-21T21:00:00+00:00 [queued]>
[2024-09-21T21:30:01.554+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_ingestion.spark_raw_ingestion_posicao scheduled__2024-09-21T21:00:00+00:00 [queued]>
[2024-09-21T21:30:01.554+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-09-21T21:30:01.576+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): spark_raw_ingestion_posicao> on 2024-09-21 21:00:00+00:00
[2024-09-21T21:30:01.581+0000] {standard_task_runner.py:57} INFO - Started process 1135 to run task
[2024-09-21T21:30:01.583+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'raw_ingestion', 'spark_raw_ingestion_posicao', 'scheduled__2024-09-21T21:00:00+00:00', '--job-id', '388', '--raw', '--subdir', 'DAGS_FOLDER/raw_ingestion.py', '--cfg-path', '/tmp/tmp420efdjl']
[2024-09-21T21:30:01.584+0000] {standard_task_runner.py:85} INFO - Job 388: Subtask spark_raw_ingestion_posicao
[2024-09-21T21:30:01.701+0000] {task_command.py:416} INFO - Running <TaskInstance: raw_ingestion.spark_raw_ingestion_posicao scheduled__2024-09-21T21:00:00+00:00 [running]> on host airflow-worker
[2024-09-21T21:30:01.886+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_ingestion' AIRFLOW_CTX_TASK_ID='spark_raw_ingestion_posicao' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-21T21:00:00+00:00'
[2024-09-21T21:30:01.887+0000] {ssh.py:141} INFO - Creating ssh_client
[2024-09-21T21:30:01.887+0000] {ssh.py:114} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2024-09-21T21:30:01.918+0000] {base.py:73} INFO - Using connection ID 'spark_ssh_default' for task execution.
[2024-09-21T21:30:01.919+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-09-21T21:30:01.927+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-09-21T21:30:02.029+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-09-21T21:30:02.030+0000] {ssh.py:478} INFO - Running command: export SPARK_HOME=/usr/local/spark; /opt/conda/bin/spark-submit --master local[*] --executor-memory 2g --conf "spark.pyspark.python=/env/venv/bin/python" /opt/shared/scripts/raw_ingestion.py 2024-09-21 posicao
[2024-09-21T21:30:04.159+0000] {ssh.py:529} WARNING - Exception in thread "main" 
[2024-09-21T21:30:04.159+0000] {ssh.py:529} WARNING - java.io.IOException: Cannot run program "/env/venv/bin/python": error=2, No such file or directory
[2024-09-21T21:30:04.160+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
[2024-09-21T21:30:04.161+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[2024-09-21T21:30:04.162+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.PythonRunner$.main(PythonRunner.scala:97)
[2024-09-21T21:30:04.162+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.PythonRunner.main(PythonRunner.scala)
[2024-09-21T21:30:04.163+0000] {ssh.py:529} WARNING - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-09-21T21:30:04.164+0000] {ssh.py:529} WARNING - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-09-21T21:30:04.164+0000] {ssh.py:529} WARNING - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-09-21T21:30:04.164+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2024-09-21T21:30:04.165+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
[2024-09-21T21:30:04.165+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
[2024-09-21T21:30:04.166+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2024-09-21T21:30:04.166+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2024-09-21T21:30:04.167+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2024-09-21T21:30:04.167+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-09-21T21:30:04.168+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-09-21T21:30:04.168+0000] {ssh.py:529} WARNING - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-09-21T21:30:04.168+0000] {ssh.py:529} WARNING - Caused by: java.io.IOException: error=2, No such file or directory
[2024-09-21T21:30:04.169+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[2024-09-21T21:30:04.170+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
[2024-09-21T21:30:04.171+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
[2024-09-21T21:30:04.171+0000] {ssh.py:529} WARNING - 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
[2024-09-21T21:30:04.171+0000] {ssh.py:529} WARNING - 	... 15 more
[2024-09-21T21:30:04.172+0000] {ssh.py:524} INFO - 24/09/21 21:30:04 INFO ShutdownHookManager: Shutdown hook called
[2024-09-21T21:30:04.176+0000] {ssh.py:524} INFO - 24/09/21 21:30:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-e9b3c356-98cd-4c43-b769-d056386d300c
[2024-09-21T21:30:04.413+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 178, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 166, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 160, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2024-09-21T21:30:04.417+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=raw_ingestion, task_id=spark_raw_ingestion_posicao, execution_date=20240921T210000, start_date=20240921T213001, end_date=20240921T213004
[2024-09-21T21:30:04.440+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 388 for task spark_raw_ingestion_posicao (SSH operator error: exit status = 1; 1135)
[2024-09-21T21:30:04.489+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-21T21:30:04.567+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
