[2024-09-21T21:18:13.776+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stage_processing.spark_stage_processing manual__2024-09-21T21:18:12.755718+00:00 [queued]>
[2024-09-21T21:18:13.783+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stage_processing.spark_stage_processing manual__2024-09-21T21:18:12.755718+00:00 [queued]>
[2024-09-21T21:18:13.784+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-09-21T21:18:13.796+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): spark_stage_processing> on 2024-09-21 21:18:12.755718+00:00
[2024-09-21T21:18:13.800+0000] {standard_task_runner.py:57} INFO - Started process 939 to run task
[2024-09-21T21:18:13.802+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stage_processing', 'spark_stage_processing', 'manual__2024-09-21T21:18:12.755718+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/stage_processing.py', '--cfg-path', '/tmp/tmpe4h07vs5']
[2024-09-21T21:18:13.803+0000] {standard_task_runner.py:85} INFO - Job 384: Subtask spark_stage_processing
[2024-09-21T21:18:13.888+0000] {task_command.py:416} INFO - Running <TaskInstance: stage_processing.spark_stage_processing manual__2024-09-21T21:18:12.755718+00:00 [running]> on host airflow-worker
[2024-09-21T21:18:14.034+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stage_processing' AIRFLOW_CTX_TASK_ID='spark_stage_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T21:18:12.755718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-21T21:18:12.755718+00:00'
[2024-09-21T21:18:14.035+0000] {ssh.py:141} INFO - Creating ssh_client
[2024-09-21T21:18:14.035+0000] {ssh.py:114} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2024-09-21T21:18:14.060+0000] {base.py:73} INFO - Using connection ID 'spark_ssh_default' for task execution.
[2024-09-21T21:18:14.060+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-09-21T21:18:14.068+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-09-21T21:18:14.161+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-09-21T21:18:14.161+0000] {ssh.py:478} INFO - Running command: export SPARK_HOME=/usr/local/spark; /opt/conda/bin/spark-submit --master local[*] --executor-memory 2g --conf "spark.pyspark.python=/env/venv/bin/python" /opt/shared/scripts/stage_processing.py 2024-09-21
[2024-09-21T21:18:16.546+0000] {ssh.py:524} INFO - Traceback (most recent call last):
[2024-09-21T21:18:16.546+0000] {ssh.py:524} INFO -   File "/opt/shared/scripts/stage_processing.py", line 5, in <module>
[2024-09-21T21:18:16.548+0000] {ssh.py:524} INFO -     from delta import DeltaTable
[2024-09-21T21:18:16.548+0000] {ssh.py:524} INFO -   File "/env/venv/lib/python3.10/site-packages/delta/__init__.py", line 17, in <module>
[2024-09-21T21:18:16.550+0000] {ssh.py:524} INFO -     from delta.tables import DeltaTable
[2024-09-21T21:18:16.551+0000] {ssh.py:524} INFO -   File "/env/venv/lib/python3.10/site-packages/delta/tables.py", line 21, in <module>
[2024-09-21T21:18:16.552+0000] {ssh.py:524} INFO -     import delta.exceptions  # noqa: F401; pylint: disable=unused-variable
[2024-09-21T21:18:16.553+0000] {ssh.py:524} INFO -   File "/env/venv/lib/python3.10/site-packages/delta/exceptions.py", line 20, in <module>
[2024-09-21T21:18:16.555+0000] {ssh.py:524} INFO -     from pyspark.errors.exceptions import captured
[2024-09-21T21:18:16.555+0000] {ssh.py:524} INFO - ModuleNotFoundError: No module named 'pyspark.errors'
[2024-09-21T21:18:16.584+0000] {ssh.py:524} INFO - 24/09/21 21:18:16 INFO ShutdownHookManager: Shutdown hook called
[2024-09-21T21:18:16.585+0000] {ssh.py:524} INFO - 24/09/21 21:18:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-970d4842-f3a6-48ee-b477-32cf181f2f01
[2024-09-21T21:18:16.675+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 178, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 166, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 160, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2024-09-21T21:18:16.678+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=stage_processing, task_id=spark_stage_processing, execution_date=20240921T211812, start_date=20240921T211813, end_date=20240921T211816
[2024-09-21T21:18:16.693+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 384 for task spark_stage_processing (SSH operator error: exit status = 1; 939)
[2024-09-21T21:18:16.702+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-21T21:18:16.737+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
